add_newline = true

# $username\
# $hostname\

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$line_break\
$character"""

[directory]
format = "[\uE0B0](fg:#81A1C1 inverted)[ $path$readonly ]($style)"
style = "fg:#81A1C1 inverted"
truncate_to_repo = false
truncation_length = 42

[git_branch]
format = "[\uE0B0](fg:#81A1C1 bg:#5E81AC)[ $symbol$branch ]($style)"
style = "bg:#5E81AC"

[git_commit]
format = "[\uE0B1](fg:#D8DEE9 bg:#5E81AC)[ \\($hash$tag\\) ]($style)"
style = "bg:#5E81AC"

[git_state]
format = '[\uE0B1](fg:#D8DEE9 bg:#5E81AC)[ \($state($progress_current/$progress_total)\) ]($style)'
style = "bg:#5E81AC"

[git_status]
format = "[\uE0B1](fg:#D8DEE9 bg:#5E81AC)[ $all_status$ahead_behind ]($style)"
style = "bg:#5E81AC"

[git_metrics]
disabled = false
added_style = "fg:green inverted"
deleted_style = "fg:red inverted"
format = "[\uE0B0](fg:#5E81AC bg:green)[ +$added ]($added_style)[\uE0B0](fg:green bg:red)[ -$deleted ]($deleted_style)[\uE0B0](fg:red)"
