add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character"""

[memory_usage]
disabled = false

[directory]
truncate_to_repo = false
truncation_length = 42

[git_metrics]
disabled = false
