add_newline = true

# $username\
# $hostname\

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$line_break\
$character"""

[directory]
format = "[\uE0B2](fg:#4C566A)[ $path$readonly ]($style)[\uE0B0](fg:#4C566A)"
style = "fg:#D8DEE9 bg:#4C566A"
truncate_to_repo = false
truncation_length = 42

[git_branch]
format = "[\uE0B0](fg:#5E81AC inverted)[ $symbol$branch ]($style)"
style = "bg:#5E81AC"

[git_commit]
format = "[\uE0B1](fg:#D8DEE9 bg:#5E81AC)([ $hash$tag ]($style))"
style = "bg:#5E81AC"

[git_state]
format = '[\uE0B1](fg:#D8DEE9 bg:#5E81AC)([ $state($progress_current/$progress_total) ]($style))'
style = "bg:#5E81AC"

[git_status]
format = "[\uE0B1](fg:#D8DEE9 bg:#5E81AC)([ $all_status$ahead_behind ]($style))"
style = "bg:#5E81AC"
ahead = "↑${count}"
diverged = "⇕↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
conflicted = "!=${count}"
staged = "+${count}"
deleted = "-${count}"
renamed = "->${count}"
untracked = "?${count}"
modified = "!${count}"
stashed = "\\$${count}"

[git_metrics]
disabled = false
added_style = "fg:green inverted"
deleted_style = "fg:red inverted"
format = "[\uE0B0](fg:#5E81AC bg:green)([ +$added ]($added_style))[\uE0B0](fg:green bg:red)([ -$deleted ]($deleted_style))[\uE0B0](fg:red)"
